apiVersion: v2
name: setup
description: Integration test setup chart for arcane operator
type: application
version: 0.0.0
appVersion: "0.0.0"
dependencies:
  - name: arcane-crd
    version: v0.0.6
    repository: oci://ghcr.io/sneaksanddata/helm