apiVersion: streaming.sneaksanddata.com/v1
kind: TestStreamDefinition
metadata:
  name: test-stream
  namespace: default
spec:
  source: "mock-source"
  destination: "mock-destination"
  suspended: false
  jobTemplateRef:
    apiVersion: streaming.sneaksanddata.com/v1beta1
    kind: StreamingJobTemplate
    name: arcane-stream-mock
    namespace: default
  backfillJobTemplateRef:
    apiVersion: streaming.sneaksanddata.com/v1beta1
    kind: StreamingJobTemplate
    name: arcane-stream-mock
    namespace: default

